[workspace]
members = ["core", "py", "json"]
resolver = "2"

[workspace.dependencies]
arrow = "=56.0.0"
arrow-array = "=56.0.0"
arrow-schema = "=56.0.0"
arrow-json = "=56.0.0"
arrow-ipc = "=56.0.0"
parquet = "=56.0.0"

[profile.bench.package.pgpq]
debug = true
